In [7]:
mi_lista=[]

In [8]:
mi_tupla=(1,2)

In [9]:
mi_lista.append(mi_tupla)

In [10]:
print(mi_lista)

[(1, 2)]


In [11]:
mi_lista.append(mi_tupla)

In [12]:
print(mi_lista)

[(1, 2), (1, 2)]


In [13]:
mi_lista.append(mi_lista)

In [14]:
print (mi_lista)

[(1, 2), (1, 2), [...]]


In [15]:
print( mi_lista[2])

[(1, 2), (1, 2), [...]]


In [16]:
lista_de_listas =[[1,2],[3,4]]

print(lista_de_listas[0][1])

## conversiones entre colecciones

In [17]:
mi_tupla = ("a","b","c","d")

In [18]:
mi_lista = list(mi_tupla)

In [19]:
print(mi_lista)

['a', 'b', 'c', 'd']


In [20]:
mi_tupla_de_nuevo=tuple(mi_lista)

In [21]:
print(mi_tupla_de_nuevo)

('a', 'b', 'c', 'd')


In [22]:
mi_set=set(mi_tupla)

In [23]:
print(mi_set)

{'c', 'd', 'b', 'a'}


In [24]:
#no existe una conversion directa entre listas, tuplas, sets y diccionarios (faltarian o bien las claves o bien los valores)

In [25]:
mi_diccionario={"Julio":2,"marta":4,"luis":0}

In [26]:
print(mi_diccionario)

{'Julio': 2, 'luis': 0, 'marta': 4}


In [27]:
print(list(mi_diccionario))

['Julio', 'luis', 'marta']


In [28]:
print(set(mi_diccionario))

{'Julio', 'luis', 'marta'}


In [29]:
print(list(mi_diccionario.items()))

[('Julio', 2), ('luis', 0), ('marta', 4)]


In [30]:
#la unica coleccion equivalente a un diccionario es una lista de tuplas con los elementos clave,valor

In [31]:
lista_de_tuplas=list(mi_diccionario.items())

In [32]:
print(lista_de_tuplas)

[('Julio', 2), ('luis', 0), ('marta', 4)]


In [33]:
diccionario_de_nuevo = dict(lista_de_tuplas)

In [34]:
print(diccionario_de_nuevo)

{'Julio': 2, 'luis': 0, 'marta': 4}


## el iterable range()

In [35]:
mi_rango=range(1001)

In [36]:
print(mi_rango)

range(0, 1001)


In [37]:
mi_lista_de_rango=list(mi_rango)

In [38]:
print(mi_lista_de_rango)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [39]:
mi_lista_del_rango=tuple(mi_rango)

In [40]:
print(mi_lista_del_rango)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [41]:
mi_lista_con_duplicados = [1,2,3,1,3,1,1]

In [42]:
#para quitar los duplicados de una lista, lo convertimos en un set

In [43]:
print(set(mi_lista_con_duplicados))

{1, 2, 3}


In [44]:
#y ahora lo convertimos de nuevo a un set

In [45]:
print(list(set(mi_lista_con_duplicados)))

[1, 2, 3]


# funciones

In [46]:
def mi_funcion(argumentos):
    #aqui va lo que hace la funcion...
    # y al final quieo que devuelva algo
    return resultado

In [47]:
#escribir una funcion que tome como argumento un numero y devuelva su doble
def mi_funcion(numero):
    return(numero**2)

In [48]:
mi_numero=4

In [49]:
mi_numero2=mi_funcion(mi_numero)

In [50]:
print(mi_numero2)

16


In [51]:
mi_numero=4.2

In [52]:
print(mi_funcion(mi_numero))

17.64


In [53]:
def cinco_por_cuatro():
    return ( 5*4 )

In [54]:
print(cinco_por_cuatro())

20


In [55]:
def multiplicar_dos_numeros(a,b):return(a*b)

In [56]:
print(multiplicar_dos_numeros(2,2))

4


In [57]:
mi_lista = [13,4,5]

In [58]:
def mayor(lista):
    maximo=0
    for item in lista:
        if( maximo < item):
            maximo=item
            print(maximo)
    return
        

In [59]:
mayor(mi_lista)

13


In [60]:
mi_lista = [2,4,1,1,6,12,3,4]

In [61]:
mayor(mi_lista)

2
4
6
12


In [62]:
mi_tupla=(2,4,5,66,6,6,6,6,6)

In [63]:
mayor(mi_tupla)

2
4
5
66


In [64]:
def meter_en_coleccion(elemento1,elemento2,elemento3=0,tipo_coleccion="lista"):
    if tipo_coleccion =="lista":
        return [ elemento1, elemento2, elemento3]
    elif tipo_coleccion =="tupla":
        return (elemento1,elemento2,elemento3)
    elif tipo_coleccion == "set":
        return {elemento1,elemento2,elemento3}
    else:
        print("Error: argumento no valido")

In [65]:
meter_en_coleccion(1,2,3,"lista")


[1, 2, 3]

In [66]:
meter_en_coleccion(1,2,4)

[1, 2, 4]

In [67]:
meter_en_coleccion(1,2,3,tipo_coleccion="set")

{1, 2, 3}

In [68]:
def f(a):a=a+1;return(a)

In [69]:
a=2
b=f(a)
print(a,b)

2 3


# List Comprehensions

In [70]:
una_lista = [1,2,3,4,5,6,7]

In [71]:
otra_lista =[]

In [72]:
for elemento in una_lista:
    otra_lista.append(elemento*3)

In [73]:
print(otra_lista)

[3, 6, 9, 12, 15, 18, 21]


In [74]:
otra_otra_lista = [elemento * 3 for elemento in una_lista] # esto se llama list comprehension

In [75]:
print( otra_otra_lista)

[3, 6, 9, 12, 15, 18, 21]


In [76]:
#para filtrar elementos

In [77]:
lista_impares = []

In [78]:
for elem in una_lista:
    if(elem%2!=0):
        lista_impares.append(elem)

In [79]:
print (lista_impares)

[1, 3, 5, 7]


In [80]:
lista_impares =[elemento for elemento in una_lista if elemento %2 !=0] #ok ok

In [81]:
print(lista_impares)

[1, 3, 5, 7]


In [82]:
#funcion zip()

In [83]:
listas_unidas=zip([1,2,3,4,5,6],["a","b","c","d","e","f"])

In [84]:
print(list(listas_unidas))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f')]


In [85]:
#funciones lambda

In [86]:
def por_dos(numero):
    return numero * 2

In [87]:
por_dos_lambda = lambda numero: numero * 2

In [88]:
a=2
print(por_dos(a),por_dos_lambda(2))

4 4


In [89]:
# funcion A (funcion B):...return(algo)

In [90]:
# A es una funcion que toma como argumento a una funcion. 

In [91]:
lista_al_cuadrado_comp=[i**2 for i in una_lista]

In [92]:
def cuadrado(numero):return numero ** 2

In [93]:
lista_alcuadrado_map=list(map(cuadrado,una_lista))

In [94]:
print(lista_alcuadrado_map)

[1, 4, 9, 16, 25, 36, 49]


In [95]:
#ahora hacemos esto con una funcion lambda

In [96]:
lista_al_cuadrado_map_lambda = list(map(lambda numero: numero **2, una_lista))

In [97]:
print(lista_al_cuadrado_map_lambda)

[1, 4, 9, 16, 25, 36, 49]


# bibliotecas

In [98]:
import math


In [99]:
print(math.factorial(4))

24


In [100]:
from math import * #con esto nos ahorramos poner math.<nombre_funcion_de_math>

# Bibliotecas especificas

* Numpy -> arrays
* Pandas -> dataframe
* SciPy -> cientifica
* Scikit-Learn -> machine learning

# Numpy

In [101]:
una_lista = [1,2,3,4,5,6,7,8,9]

In [102]:
lista_por_escalar =[12 * elemento for elemento in una_lista]

In [103]:
una_matriz = [[1,2,4],[4,5,6],[7,8,9]]

In [104]:
escalar = 12
resultado_final =[]
resultado_de_cada_fila = []
for fila in una_matriz:
    for elemento in fila:
        resultado_de_cada_fila.append(elemento * escalar)
    resultado_final.append(resultado_de_cada_fila)
    resultado_de_cada_fila = []

In [105]:
print(resultado_final)

[[12, 24, 48], [48, 60, 72], [84, 96, 108]]


In [106]:
#ahora lo hacemos con numpy

In [107]:
import numpy

In [108]:
nuestro_primer_array = numpy.array([1,2,3,4])

In [109]:
print(nuestro_primer_array)

[1 2 3 4]


In [110]:
type(nuestro_primer_array)

numpy.ndarray

In [111]:
nuestro_primer_array * 4

array([ 4,  8, 12, 16])

In [112]:
matriz = numpy.array([[1,2,3],[4,5,6],[7,8,9]])

In [113]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
matriz * 4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

## creando arrays

In [115]:
import numpy as np

In [116]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [117]:
#entran enteros y decimales.dtype

In [118]:
enteros_y_decimales = np.array([1,2.0,3,4.6])

In [119]:
enteros_y_decimales.dtype

dtype('float64')

In [120]:
#numpy tienen un monton de tipos de datos nuevos

In [121]:
enteros = np.array([1,2,3,4,5,6])

In [122]:
enteros.dtype

dtype('int64')

In [123]:
mi_matriz = np.array([[1,2],
                    [3,4],
                    [5,6]])

In [124]:
mi_matriz.shape

(3, 2)

In [125]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [126]:
np.identity(7)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [127]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [128]:
np.arange(3,14)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [129]:
import numpy as np
mi_vector=np.arange(3,14,2)# el "2" es el paso
print (mi_vector)

[ 3  5  7  9 11 13]


In [130]:
mi_vector.reshape((3,4))

ValueError: total size of new array must be unchanged

# Operaciones

In [131]:
matriz = np.arange(0.0,20.0).reshape((4,5))# crea una matriz de 4 filas  y 5 columnas y la rellena con numeros del 0 al 20

In [132]:
matriz

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.]])

In [133]:
matriz * matriz

array([[   0.,    1.,    4.,    9.,   16.],
       [  25.,   36.,   49.,   64.,   81.],
       [ 100.,  121.,  144.,  169.,  196.],
       [ 225.,  256.,  289.,  324.,  361.]])

In [134]:
#element wise multiplication, NO ES UNA MULTIPLICACION DE MATRICES CLASICA

In [135]:
matriz + matriz

array([[  0.,   2.,   4.,   6.,   8.],
       [ 10.,  12.,  14.,  16.,  18.],
       [ 20.,  22.,  24.,  26.,  28.],
       [ 30.,  32.,  34.,  36.,  38.]])

In [136]:
matriz.T # traspuesta

array([[  0.,   5.,  10.,  15.],
       [  1.,   6.,  11.,  16.],
       [  2.,   7.,  12.,  17.],
       [  3.,   8.,  13.,  18.],
       [  4.,   9.,  14.,  19.]])

# ufuncs de Numpy

In [137]:
#raiz cuadrada de cada elemento
np.sqrt(matriz)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ],
       [ 3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739],
       [ 3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894]])

In [138]:
np.cos(matriz)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722],
       [-0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462]])

In [139]:
otra_matriz = np.arange(20,40).reshape((4,5))
print(matriz)
print("")
print(otra_matriz)

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]]

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [140]:
np.maximum(matriz,otra_matriz)

array([[ 20.,  21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.,  29.],
       [ 30.,  31.,  32.,  33.,  34.],
       [ 35.,  36.,  37.,  38.,  39.]])

## indexado y slices de arrays de np

In [141]:
mi_array = np.array(["perro","gato","loro","lince","python","oso","equidna"])

In [142]:
mi_array.dtype

dtype('<U7')

In [143]:
#acceder a gato:
mi_array[1]

'gato'

In [144]:
mi_array[3:6]

array(['lince', 'python', 'oso'], 
      dtype='<U7')

In [145]:
mi_array[3:6]="tigre"

In [146]:
mi_array

array(['perro', 'gato', 'loro', 'tigre', 'tigre', 'tigre', 'equidna'], 
      dtype='<U7')

In [147]:
#siempre transformar el array en uno nuevo

In [148]:
matriz

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.]])

In [167]:
matriz[:,3] #cuarta columna
matriz[0,:] #primera fila
matriz[:3]  #3 primeras filas
matriz[0:1] #primera fila
matriz[:2]

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [150]:
#tambien se puede hacer
matriz[1,2]

7.0

In [151]:
matriz[:]

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.]])

In [152]:
matriz[:]

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.]])

In [200]:
matriz[:3] #todas las columnas de las 3 primeras filas

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.]])

In [171]:
matriz[3:] #todas las columnas de la tercera fila hasta el final

array([[ 15.,  16.,  17.,  18.,  19.]])

In [172]:
matriz[2:3] #las filas comprendidas entre la posicion 2 inclusive y 3 exclusive

array([[ 10.,  11.,  12.,  13.,  14.]])

In [203]:
# todas las filas de la tercera columna
matriz[:,3]

array([  3.,   8.,  13.,  18.])

In [204]:
# todas la columnas de la tercera fila
matriz[3,:]

array([ 15.,  16.,  17.,  18.,  19.])

In [175]:
#o tambien
matriz[0] #devuelve la primera fila

array([ 5.,  6.,  7.,  8.,  9.])

In [206]:
un_array = np.array(["juilio","jose","alberto","julio","Nuria","paco"])

In [207]:
un_array

array(['juilio', 'jose', 'alberto', 'julio', 'Nuria', 'paco'], 
      dtype='<U7')

In [208]:
un_array == "Julio"

array([False, False, False, False, False, False], dtype=bool)

In [209]:
#recorre todos los elementos y devuelve quien satisfaga la condicion

In [210]:
array_booleanos = np.array([True,False,False,True,False])

In [211]:
array_lugares = np.array(["EEUU","España","China","Haway","Arabia Saudi"])

In [213]:
array_lugares[array_booleanos]

array(['EEUU', 'Haway'], 
      dtype='<U12')

In [214]:
#va elemento a elemento y devuelve los True

In [216]:
un_array[un_array=="julio"]

array(['julio'], 
      dtype='<U7')

In [217]:
numeros = np.arange(0,500)

In [218]:
numeros[numeros % 2 ==0]

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [219]:
#filtros "and"
numeros[(numeros % 2 ==0)&(numeros > 250)]

array([252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276,
       278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302,
       304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328,
       330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354,
       356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380,
       382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406,
       408, 410, 412, 414, 416, 418, 420, 422, 424, 426, 428, 430, 432,
       434, 436, 438, 440, 442, 444, 446, 448, 450, 452, 454, 456, 458,
       460, 462, 464, 466, 468, 470, 472, 474, 476, 478, 480, 482, 484,
       486, 488, 490, 492, 494, 496, 498])

## Metodos estadisticos con Numpy

In [221]:
mi_array = np.arange(0,11)

In [223]:
mi_array.sum()

55

In [225]:
mi_array.mean()

5.0

In [227]:
mi_array.var()

10.0

In [228]:
mi_array.min()

0

# multiplicar matrices ( de verdad )

In [229]:
mi_matriz = np.arange(0,12).reshape(3,4)

In [230]:
mi_matriz_traspuesta = mi_matriz.T

In [234]:
print(mi_matriz)
print("")
print(mi_matriz_traspuesta)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [235]:
matrices_multiplicadas = np.dot(mi_matriz,mi_matriz_traspuesta)

In [236]:
matrices_multiplicadas

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [237]:
mi_matriz.dot(mi_matriz_traspuesta)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [238]:
#inversa de una matriz

In [240]:
#np.linalg -> es un subconjunto para algebra lineal de numpy

In [241]:
#np.linalg.inv( <matriz_cuadrada_no_singular>)

In [243]:
numeros_de_una_normal=np.random.normal(0,1,(10,3))

In [244]:
numeros_de_una_normal.mean()

-0.29806359608413519

In [245]:
numeros_de_una_normal.std()

1.086953420999982

In [246]:
numeros_entre_o_y_15=np.random.randint(0,16,(4,3))

In [247]:
numeros_entre_o_y_15

array([[ 3, 14,  1],
       [ 5, 14, 12],
       [ 9, 10, 13],
       [ 9, 15, 13]])

In [248]:
uniforme = np.random.uniform(-10,10,(5,4))

In [249]:
uniforme

array([[ 6.56371794,  4.90773057, -9.20078148, -3.71243536],
       [-4.34753361,  0.85703997, -4.38303098, -1.54588251],
       [ 0.18169277,  6.20971748,  2.05177011,  0.68400227],
       [-5.32754496, -1.77647227, -0.03507227,  9.7787746 ],
       [-3.61116575,  4.43079811,  0.41959685, -3.48735445]])